### ISSUE TITLE
When installed system wide, the temp robots file isn't writeable.

### ISSUE THREAD

**Issue by rameshvarun** [yterajima/middleman-robots#10]
This gem writes `robots.txt` to a source-relative directory. However, if the gem is installed system-wide as is default on Ubuntu, we do not have permissions to write to it unless `middleman` commands are prefaced with `sudo`.

Furthermore, this could also cause problems if two `middleman server` commands are running at the same time - they would overwrite each other's `robots.txt` files.

**Comment by tisba** [comment]
I'm wondering why middleman-robots even tries to do that...

I think the problem lies here:

https://github.com/yterajima/middleman-robots/blob/704050edeecaaab3e76f3f2db34b0cb39e9c02a8/lib/middleman-robots/extension.rb#L23-L31

I haven't fully followed the code, but I think we rather want to have something like this (https://ruby-doc.org/stdlib-2.5.1/libdoc/tempfile/rdoc/Tempfile.html):

```ruby
file = Tempfile.new('foo')
begin
   ...do something with file...
ensure
   file.close
   file.unlink   # deletes the temp file
end
```

`Tempfile` will take care of generating a temporary, collision free name and a location that can be written to.

**Comment by tisba** [comment]
-bump-

The issue still persists currently and is quite annoying :-/ It would be great if we could some guidance in order to prepare a patch to resolve this issue...

**Comment by rameshvarun** [comment]
I typically just work around this by running `bundle install --path vendor/bundle` to have bundler install gems to a project-local directory rather than system-wide.
